{
 "title": "CDN监控",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": "xxxxxxxxxxxxxxxxxxx" }
  ]
 },
 "panels": [
  {
   "title": "CDN流量",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "BPS",
     "period": "60",
     "project": "acs_cdn",
     "target": [
      "Average",
      "Minimum",
      "Maximum"
     ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Average",
      "Minimum",
      "Maximum"
     ]
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "QPS",
     "period": "60",
     "project": "acs_cdn",
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Average",
      "Minimum",
      "Maximum"
     ]
    }
   ]
  },
  {
   "title": "命中率",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "hitRate",
     "period": "60",
     "project": "acs_cdn",
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Average",
      "Minimum",
      "Maximum"
     ]
    }
   ]
  },
  {
   "title": "错误率",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "4xx",
     "dimensions": [ "$instance" ],
     "metric": "Usercode4xx",
     "period": "60",
     "project": "acs_cdn",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    },
    {
     "describe": "5xx",
     "dimensions": [ "$instance" ],
     "metric": "Usercode5xx",
     "period": "60",
     "project": "acs_cdn",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  }
 ]
}