{
 "title": "ECS监控",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "{\"instanceId\":\"i-xxxxxxxxxxx\"}, {\"instanceId\":\"i-xxxxxxxxxxx\"}"
   },
   {
    "name": "disk",
    "query": "{\"device\":\"/dev/vda1\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "cpu_total",
     "period": "60",
     "project": "acs_ecs_dashboard",
     "target": [
      "Average",
      "Maximum"
     ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Average",
      "Maximum"
     ]
    }
   ]
  },
  {
   "title": "MEMORY",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "memory_usedspace",
     "period": "60",
     "project": "acs_ecs_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    },
    {
     "dimensions": [ "$instance" ],
     "metric": "memory_totalspace",
     "period": "60",
     "project": "acs_ecs_dashboard",
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "VPC公网入站带宽",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "VPC_PublicIP_InternetInRate",
     "period": "60",
     "project": "acs_ecs_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "VPC公网出站带宽",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "VPC_PublicIP_InternetOutRate",
     "period": "60",
     "project": "acs_ecs_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "每秒从系统磁盘读取的字节数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "DiskReadBPS",
     "period": "60",
     "project": "acs_ecs_dashboard",
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Average",
      "Maximum",
      "Minimum"
     ]
    }
   ]
  },
  {
   "title": "每秒写入系统磁盘的字节数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "DiskWriteBPS",
     "period": "60",
     "project": "acs_ecs_dashboard",
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Average",
      "Maximum",
      "Minimum"
     ]
    }
   ]
  },
  {
   "title": "每秒在系统磁盘上执行的读取操作数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "DiskReadIOPS",
     "period": "60",
     "project": "acs_ecs_dashboard",
     "target": [
      "Average",
      "Maximum",
      "Minimum"
     ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Average",
      "Maximum",
      "Minimum"
     ]
    }
   ]
  },
  {
   "title": "每秒在系统磁盘上执行的写操作数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "DiskWriteIOPS",
     "period": "60",
     "project": "acs_ecs_dashboard",
     "target": [
      "Average",
      "Maximum",
      "Minimum"
     ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Average",
      "Maximum",
      "Minimum"
     ]
    }
   ]
  },
  {
   "title": "负载_1m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "load_1m",
     "period": "60",
     "project": "acs_ecs_dashboard",
     "target": [
      "Average",
      "Maximum",
      "Minimum"
     ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Average",
      "Maximum",
      "Minimum"
     ]
    }
   ]
  },
  {
   "title": "负载_15m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "load_15m",
     "period": "60",
     "project": "acs_ecs_dashboard",
     "target": [
      "Average",
      "Maximum",
      "Minimum"
     ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Average",
      "Maximum",
      "Minimum"
     ]
    }
   ]
  },
  {
   "title": "主硬盘使用量",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance;$disk" ],
     "metric": "diskusage_used",
     "period": "900",
     "project": "acs_ecs_dashboard",
     "target": [
      "Maximum",
      "Average",
      "Minimum"
     ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Maximum",
      "Average",
      "Minimum"
     ]
    }
   ]
  }
 ]
}