{
 "title": "REDIS监控",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "{\"instanceId\":\"XXXXXX\"}, {\"instanceId\":\"XXXXXX\"}"
   }
  ]
 },
 "panels": [
  { "title": "dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "CpuUsage",
     "period": "60",
     "project": "acs_kvstore",
     "target": [
      "Maximum",
      "Minimum",
      "Average"
     ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Maximum",
      "Minimum",
      "Average"
     ]
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "MemoryUsage",
     "period": "60",
     "project": "acs_kvstore",
     "target": [
      "Maximum",
      "Minimum",
      "Average"
     ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Maximum",
      "Minimum",
      "Average"
     ]
    }
   ]
  },
  {
   "title": "连接数使用率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "ConnectionUsage",
     "period": "60",
     "project": "acs_kvstore",
     "target": [
      "Maximum",
      "Minimum",
      "Average"
     ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Maximum",
      "Minimum",
      "Average"
     ]
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "UsedQPS",
     "period": "60",
     "project": "acs_kvstore",
     "target": [
      "Maximum",
      "Average"
     ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Maximum",
      "Average"
     ]
    }
   ]
  },
  {
   "title": "内存",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "UsedMemory",
     "period": "60",
     "project": "acs_kvstore",
     "target": [
      "Maximum",
      "Average"
     ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Maximum",
      "Average"
     ]
    }
   ]
  },
  {
   "title": "连接数",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "UsedConnection",
     "period": "60",
     "project": "acs_kvstore",
     "target": [
      "Maximum",
      "Average"
     ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Maximum",
      "Average"
     ]
    }
   ]
  },
  {
   "title": "KEYS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "StandardKeys",
     "period": "60",
     "project": "acs_kvstore",
     "target": [
      "Maximum",
      "Minimum",
      "Average"
     ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Maximum",
      "Minimum",
      "Average"
     ]
    }
   ]
  },
  {
   "title": "命中率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "StandardHitRate",
     "period": "60",
     "project": "acs_kvstore",
     "target": [
      "Maximum",
      "Minimum",
      "Average"
     ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Maximum",
      "Minimum",
      "Average"
     ]
    }
   ]
  },
  {
   "title": "缓存失败数量",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "FailedCount",
     "period": "60",
     "project": "acs_kvstore",
     "target": [
      "Maximum",
      "Minimum",
      "Average"
     ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Maximum",
      "Minimum",
      "Average"
     ]
    }
   ]
  },
  {
   "title": "内网入站流量",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "IntranetIn",
     "period": "60",
     "project": "acs_kvstore",
     "target": [
      "Maximum",
      "Minimum",
      "Average"
     ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Maximum",
      "Minimum",
      "Average"
     ]
    }
   ]
  },
  {
   "title": "内网出站流量",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "IntranetOut",
     "period": "60",
     "project": "acs_kvstore",
     "target": [
      "Maximum",
      "Minimum",
      "Average"
     ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Maximum",
      "Minimum",
      "Average"
     ]
    }
   ]
  }
 ]
}