{
 "title": "RDS监控",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "{\"instanceId\":\"xxxx\"}, {\"instanceId\":\"xxxx\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "CpuUsage",
     "project": "acs_rds_dashboard",
     "target": [
      "Average",
      "Minimum",
      "Maximum"
     ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Average",
      "Minimum",
      "Maximum"
     ]
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "MemoryUsage",
     "project": "acs_rds_dashboard",
     "target": [
      "Average",
      "Minimum",
      "Maximum"
     ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Average",
      "Minimum",
      "Maximum"
     ]
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "DiskUsage",
     "project": "acs_rds_dashboard",
     "target": [
      "Average",
      "Minimum",
      "Maximum"
     ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Average",
      "Minimum",
      "Maximum"
     ]
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "MySQL_QPS",
     "project": "acs_rds_dashboard",
     "target": [
      "Average",
      "Minimum",
      "Maximum"
     ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Average",
      "Minimum",
      "Maximum"
     ]
    }
   ]
  },
  {
   "title": "TPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "MySQL_TPS",
     "project": "acs_rds_dashboard",
     "target": [
      "Average",
      "Minimum",
      "Maximum"
     ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Average",
      "Minimum",
      "Maximum"
     ]
    }
   ]
  },
  {
   "title": "IOPS使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "IOPSUsage",
     "project": "acs_rds_dashboard",
     "target": [
      "Average",
      "Minimum",
      "Maximum"
     ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [
      "Average",
      "Minimum",
      "Maximum"
     ]
    }
   ]
  },
  {
   "title": "每秒发送到MySQL数据库的数据量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "MySQL_NetworkInNew",
     "project": "acs_rds_dashboard",
     "target": [ "Maximum" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "每秒从MySQL数据库发送的数据量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "MySQL_NetworkOutNew",
     "project": "acs_rds_dashboard",
     "target": [ "Maximum" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "每秒实例上的活动连接数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "MySQL_ActiveSessions",
     "project": "acs_rds_dashboard",
     "target": [ "Maximum" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "慢查询数量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$instance" ],
     "metric": "MySQL_SlowQueries",
     "project": "acs_rds_dashboard",
     "target": [ "Maximum" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Maximum" ]
    }
   ]
  }
 ]
}